<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-03-30T16:27:35Z" name="Default suite" finished-at="2019-03-30T16:28:05Z" duration-ms="29879">
    <groups>
    </groups>
    <test started-at="2019-03-30T16:27:35Z" name="Default test" finished-at="2019-03-30T16:28:05Z" duration-ms="29879">
      <class name="scenarios.srinidhi.assignment.twenty.BluestoneGMnextverify_fourteen">
        <test-method signature="f()[pri:0, instance:scenarios.srinidhi.assignment.twenty.BluestoneGMnextverify_fourteen@158a8276]" started-at="2019-03-30T16:27:35Z" name="f" finished-at="2019-03-30T16:28:05Z" duration-ms="29643" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1,000] but found [Rs 1,000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1,000] but found [Rs 1,000]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at scenarios.srinidhi.assignment.twenty.BluestoneGMnextverify_fourteen.f(BluestoneGMnextverify_fourteen.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- scenarios.srinidhi.assignment.twenty.BluestoneGMnextverify_fourteen -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
